name: fitfoot
description: "Fit Foot."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9

  # Firebase Integration
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.5.3

  # Notifications
  flutter_local_notifications: ^17.2.2

  # Connectivity
  connectivity_plus: ^6.0.5

  # Network Requests
  dio: ^5.6.0
  http: ^1.2.2

  # Local Storage
  shared_preferences: ^2.3.2

  # State Management and Dependency Injection
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5

  # Authentication
  google_sign_in: ^6.2.1

  # Image Handling
  image_picker: ^1.0.4

  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Social Sharing
  share_plus: ^10.0.0

  sqflite: ^2.3.3+1
  #  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.11
  floor: ^1.5.0
  path: any
  intl: ^0.19.0


  cached_network_image: ^3.4.0
  flutter_blurhash: ^0.6.0
  url_launcher: ^6.3.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  camera:
  webview_flutter: ^4.0.5 # Check for the latest version
  permission_handler: ^11.3.1
  flutter_stripe: ^11.1.0
  country_flags: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
